<?php
/**
 * Created by PhpStorm.
 * User: ankur
 * Date: 19/1/17
 * Time: 3:05 PM
 */

namespace MyApp\controllers;

use MyApp\helpers\ArticleHelper;
use MyApp\Slim;

/**
 * Class AccountsController
 * @package MyApp\controllers
 */
class AccountsController extends Controller {

	protected $helper;

	function __construct(Slim $app) {
		$this->helper = ArticleHelper::getInstance();
		parent::__construct($app); // TODO: Change the autogenerated stub
	}

	function routes() {
		$this->app->get('/accounts/findall',[$this,'getAccounts'])->name("findAll");
	}

	/**
	 *
	 */
	public function getAccounts(){
		$this->app->getLog()->info("this is good");
		$accounts = $this->findAllAccounts();
			$this->setHttpStatus(($accounts) ? 200 : 204);
			$this->response->setData($accounts->toArray());
			$this->respond();
	}

	/**
	 * @return \Accounts[]|\Propel\Runtime\Collection\ObjectCollection
	 */
	protected function findAllAccounts() {
		$accounts = \AccountsQuery::create()
			->paginate($page = 2, $rowsPerPage = 30);

		;

		return $accounts;

	}

}