<?php
/**
 * Created by PhpStorm.
 * User: Ankur Garg
 * Date: 30/3/17
 * Time: 3:39 PM
 */

namespace MyApp\controllers;

use MyApp\APIRoutes;
use MyApp\components\ESHelper;
use MyApp\helpers\ArticleHelper;
use MyApp\helpers\PitchVisionUtils;
use MyApp\request\ArticleRequest;
use MyApp\Slim;

class ArticleWebController extends Controller {

	protected $helper;

	function __construct(Slim $app) {
		$this->helper = ArticleHelper::getInstance();
		parent::__construct($app); // TODO: Change the autogenerated stub
	}

	protected function routes() {
		$this->app->get('/article-web/findall', [$this, 'getArticlesWeb'])->name("findAll");
		$this->app->map('/article-web/create', [$this, 'createArticleWeb'])->via('GET', 'POST');
		$this->app->map('/article-web/update/:id', [$this, 'updateArticleWeb'])->name("update")->via('GET', 'PUT');
		$this->app->delete('/article-web/delete', [$this, 'deleteArticleWeb'])->name("Delete");

		$this->app->get("/article-web/search/:q",[$this, 'searchFromES'])->name("search");
	}

	public function getArticlesWeb() {
		$articles = $this->helper->findArticles();
		$params = [
			'data' => $articles,
			'base_url' => $this->app->baseUrl,
			'title' => 'Listing all articles'
		];
		echo $this->app->twig->render(APIRoutes::GROUP_ARTICLE_WEB . "/view-articles.html.twig", $params);
	}

	public function createArticleWeb() {

		if ($this->app->request->isPost()) {
			$this->_validate(ArticleRequest::creatingRule());
			$allPostVar = $this->app->request()->post();
			$article = new ArticleRequest();
			$article->loadFromAPI($allPostVar);
			$status = $this->helper->saveArticle($article);
			if ($status) {
				$this->app->flash('success', 'Record Updated sucessfully');
				$this->app->redirect($this->app->baseUrl . '/article-web/findall');
			}
		}
		$authors = PitchVisionUtils::arrayMap($this->helper->getAuthors()->toArray(), 'Id', 'AuthorName');
		$params = [
			'base_url' => $this->app->baseUrl,
			'title' => 'Create Articles',
			'authors' => $authors
		];
		echo $this->app->twig->render(APIRoutes::GROUP_ARTICLE_WEB . "/add-article.html.twig", $params);
	}

	/**
	 * @throws \Exception
	 */
	public function updateArticleWeb() {
		if ($this->app->request->isPut()) {
			$this->_validate(ArticleRequest::creatingRule());
			$allPostVar = $this->app->request->post();
			$model = new ArticleRequest();
			$model->loadFromAPI($allPostVar);
			$response = $this->helper->updateArticle($model);
			if ($response) {
				$this->app->flash('success', 'Record Updated sucessfully');
				$this->app->redirect($this->app->baseUrl . '/article-web/findall');
			}
		}
		$article = $this->helper->findArticle($this->app->router->getCurrentRoute()->getParam('id'));
		$authors = PitchVisionUtils::arrayMap($this->helper->getAuthors()->toArray(), 'Id', 'AuthorName');
		$params = [
			'data' => $article->toArray(),
			'base_url' => $this->app->baseUrl,
			'title' => 'Edit Articles',
			'authors' => $authors
		];
		echo $this->app->twig->render(APIRoutes::GROUP_ARTICLE_WEB . "/edit-article.html.twig", $params);
	}

	public function deleteArticleWeb() {
		$allPostVar = $this->app->request->post();
		if (!isset($allPostVar['id']) || empty($allPostVar['id'])) {
			$this->app->redirect($this->app->baseUrl . '/article-web/findall');
		}
		$this->app->flash('success', 'Record Deleted');
		$articleId = $allPostVar['id'];
		$this->helper->deleteArticle($articleId);
		$this->app->redirect($this->app->baseUrl . '/article-web/findall');
	}


	public function searchFromES() {
		$term = $this->app->router->getCurrentRoute()->getParams();
		if (!isset($term['q'])) {
			$this->app->redirect($this->app->baseUrl . '/article-web/findall');
		}
		$client =new ESHelper();
		$params = [
			'index' => 'monolog',
			'type' => 'api',
			'body' => [
				'query' => [
					'match' => [
						'_all' =>$term['q'],
					]
				],
				'size' =>ESHelper::DEFAULT_SIZE,
			]
		];


		$result = $client->query($params);
		$hits = isset($result['hits']['hits']) ? $result['hits']['hits'] : [];
		$params = [
			'base_url' => $this->app->baseUrl,
			'title' => "Search Result for ".$term['q'],
			'hits' => $hits
		];
		echo $this->app->twig->render(APIRoutes::GROUP_ARTICLE_WEB . "/search-result.html.twig", $params);
	}
}