<?php
/**
 * Created by PhpStorm.
 * User: ashima
 * Date: 19/1/17
 * Time: 3:05 PM
 */

namespace MyApp\controllers;

use MyApp\helpers\AuthorHelper;
use MyApp\request\AuthorRequest;
use MyApp\Slim;

/**
 * Class ArticleController
 * @package MyApp\controllers
 */
class AuthorController extends Controller {

	protected $helper;

	function __construct(Slim $app) {
		$this->helper = AuthorHelper::getInstance();
		parent::__construct($app); // TODO: Change the autogenerated stub
	}

	function routes() {
		$this->app->get('/author/find/:id',[$this,'getAuthor'])->name("find");
		$this->app->get('/author/findall',[$this,'getAuthors'])->name("findAll");
//		$this->app->post('/author/create',$this->validate((new AuthorRequest())->rule()),[$this,'createArticle'])->name("create");
	}


	public function getAuthor(){
		$article = $this->helper->findAuthor($this->app->router->getCurrentRoute()->getParam('id'));
		$this->setHttpStatus(($article)?200:204);
		$this->response->setData($article->toArray());
		$this->respond();
	}

	/**
	 *
	 */
	public function getAuthors(){
		$this->app->getLog()->info("this is good");
		$authors = $this->helper->findAuthors();
		$this->setHttpStatus(($authors) ? 200 : 204);
		$this->response->setData($authors->toArray());
		$this->respond();
	}


	public function createAuthor(){
		$allPostVar =$this->app->request->post();
		$author = new AuthorRequest();
		$author->loadFromAPI($allPostVar);
		$status = $this->helper->saveAuthor($author);
		if($status){
			$data = ['message'=>'created sucessfully'];
			$this->setHttpStatus(($data)?201:404);
			$this->response->setData($data);
			$this->respond();
		}
	}



}