<?php
/**
 * Created by PhpStorm.
 * User: ashima
 * Date: 19/1/17
 * Time: 3:05 PM
 */

namespace MyApp\controllers;

use Slim\Slim;

class DemoController extends BaseController{
	function __construct(Slim $app) {
		parent::__construct($app); // TODO: Change the autogenerated stub
	}
	public function create(){
		echo "Validation pass";
	}

	public function read(){
		echo "You are in read of ".self::class;
	}

	public function dos(){
		echo "You are in dos of ".self::class;
	}

}

